name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: trading-cz/github_action/.github/workflows/python-ci.yml@main
    with:
      python-version: '3.12'
      source-dir: 'src/tradingcz'
      test-dir: tests
      run-pylint: true
      run-mypy: true
      run-ruff: true
